# SPDX-License-Identifier: GPL-2.0
include ../../../scripts/Makefile.include

top_srcdir = $(abspath ../../../..)

KSFT_KHDR_INSTALL := 1
include ../lib.mk

TEST_PROGS += ./run.sh
TEST_FILES := setup.py setup.cfg tcp_authopt_test
